# Generated by Django 4.0 on 2021-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
