# Generated by Django 4.0 on 2021-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0003_myuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='location_pincode',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
