# Generated by Django 4.0 on 2021-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_myuser_location_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='location_pincode',
            field=models.CharField(max_length=6),
        ),
    ]
