# Generated by Django 4.0 on 2021-12-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0005_alter_myuser_location_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='location_pincode',
        ),
    ]
