# Generated by Django 4.0 on 2021-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0006_remove_myuser_location_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='business_pincode',
            field=models.CharField(default=400065, max_length=6),
        ),
    ]
