# Generated by Django 4.0 on 2021-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0007_myuser_business_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='business_pincode',
            field=models.CharField(max_length=6),
        ),
    ]
