# Generated by Django 4.0 on 2021-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_cart',
            name='final_cart_pincode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
