# Generated by Django 4.0 on 2021-12-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem'),
        ),
    ]
