# Generated by Django 3.0.14 on 2021-12-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211219_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderItem'),
        ),
    ]
