# Generated by Django 4.0 on 2021-12-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_final_cart_final_cart_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_cart',
            name='final_cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem'),
        ),
    ]
