# Generated by Django 4.0 on 2021-12-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_alter_myuser_is_active'),
        ('main', '0002_itemtype_created_by_orderitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_signup.myuser'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_signup.myuser'),
        ),
    ]
