# Generated by Django 4.0 on 2021-12-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/default-product-image.jpg', upload_to='images/'),
        ),
    ]
