# Generated by Django 4.0 on 2021-12-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_final_cart_final_cart_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='final_cart',
            options={'ordering': ['final_cart_pincode', 'final_cart_item']},
        ),
        migrations.AlterField(
            model_name='final_cart',
            name='final_cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem'),
        ),
    ]
