# Generated by Django 4.0 on 2021-12-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_ordered_items_order_ordered_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
