# Generated by Django 4.0 on 2021-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_final_cart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH ON DELIVERY', 'CASH ON DELIVERY'), ('CARD ON DELIVERY', 'CARD ON DELIVERY')], max_length=100),
        ),
    ]
