# Generated by Django 4.0 on 2021-12-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderitem_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('final_cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
            ],
        ),
    ]
