# Generated by Django 4.0 on 2021-12-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0008_alter_myuser_business_pincode'),
        ('main', '0007_final_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_cart',
            name='sold_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_signup.myuser'),
        ),
    ]
